# Generated by Django 3.2.8 on 2021-10-16 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompany',
            name='company',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='employeecompany',
            name='position',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='compnay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='employeeskills',
            name='languages',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='patronymic',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='employees',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employeeskills',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employeeskills',
            name='skill_level',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
