# Generated by Django 3.2.8 on 2021-10-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeecompany_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecompany',
            old_name='employees',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='employeeskills',
            name='compnay',
        ),
        migrations.RemoveField(
            model_name='employeeskills',
            name='languages',
        ),
        migrations.AddField(
            model_name='employee',
            name='anguages',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
