# Generated by Django 3.2.8 on 2021-10-17 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeecompany_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=15)),
                ('skill_level', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'EmployeeSkill',
                'verbose_name_plural': 'EmployeeSkills',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeecompany',
            options={'verbose_name': 'EmployeeCompany', 'verbose_name_plural': 'EmployeeCompanies'},
        ),
        migrations.RemoveField(
            model_name='employeecompany',
            name='employees',
        ),
        migrations.AddField(
            model_name='employee',
            name='languages',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeecompany',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.DeleteModel(
            name='EmployeeSkills',
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
    ]
