# Generated by Django 3.2.8 on 2021-10-16 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0005_auto_20211016_2042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeSkills',
            new_name='EmployeeSkill',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeecompany',
            options={'verbose_name': 'EmployeeCompany', 'verbose_name_plural': 'EmployeeCompanies'},
        ),
        migrations.AlterModelOptions(
            name='employeeskill',
            options={'verbose_name': 'EmployeeSkill', 'verbose_name_plural': 'EmployeeSkills'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='anguages',
            new_name='languages',
        ),
        migrations.AlterField(
            model_name='employeecompany',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
