# Generated by Django 3.2.8 on 2021-10-17 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_user'),
        ('employees', '0007_auto_20211016_2103'),
    ]

    operations = [
    ]
