# Generated by Django 3.2.8 on 2021-10-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='companycollaboration',
            name='collaboration_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.RemoveField(
            model_name='companycollaboration',
            name='companies',
        ),
        migrations.AddField(
            model_name='companycollaboration',
            name='companies',
            field=models.ManyToManyField(blank=True, null=True, to='companies.Company'),
        ),
    ]
