# Generated by Django 3.2.8 on 2021-10-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycollaboration',
            name='companies',
            field=models.ManyToManyField(blank=True, to='companies.Company'),
        ),
    ]
