import enum


class CompanyErrorMessages(enum.Enum):
    REQUEST_FIELDS_ERROR = "REQUEST_FIELDS_ERROR"
    NON_UNIQUE_COMPANY_NAME_ERROR = "NON_UNIQUE_COMPANY_NAME_ERROR"
    NON_UNIQUE_COMPANY_OFFICE_ERROR = "NON_UNIQUE_COMPANY_OFFICE_ERROR"
    COMPANY_DOES_NOT_EXISTS = "COMPANY_DOES_NOT_EXISTS"
    COMPANY_OFFICE_DOES_NOT_EXISTS = "COMPANY_OFFICE_DOES_NOT_EXISTS"