# Generated by Django 3.2.8 on 2021-10-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycollaboration',
            name='companies',
        ),
        migrations.AddField(
            model_name='companycollaboration',
            name='companies',
            field=models.ManyToManyField(blank=True, null=True, to='companies.Company'),
        ),
    ]
