# Generated by Django 3.2.8 on 2021-10-17 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companycollaboration_collaboration_name'),
        ('companies', '0005_alter_company_user'),
    ]

    operations = [
    ]
